const EXAM_WORD_BANKS = {
  gaokao: [
    ["abandon", "放弃；抛弃", "Never abandon your dream when things become difficult."],
    ["absorb", "吸收；理解", "Plants absorb water from the soil."],
    ["academic", "学术的", "She is interested in academic research."],
    ["access", "通道；使用权", "Students have access to the online library."],
    ["accompany", "陪伴；伴随", "Music often accompanies the film."],
    ["accumulate", "积累", "Good habits accumulate over time."],
    ["accurate", "准确的", "The report gives accurate information."],
    ["adapt", "适应；改编", "We need to adapt to the new environment."],
    ["adequate", "足够的；合适的", "The room has adequate light."],
    ["adjust", "调整；适应", "Please adjust the seat before driving."],
    ["advocate", "提倡；拥护者", "Many people advocate a low-carbon lifestyle."],
    ["alternative", "可替代的；选择", "We need an alternative plan."],
    ["analyze", "分析", "The teacher asked us to analyze the passage."],
    ["anticipate", "预料；期待", "We anticipate a rise in temperature."],
    ["appreciate", "欣赏；感激", "I appreciate your help."],
    ["approach", "方法；接近", "This approach is simple and useful."],
    ["appropriate", "合适的", "Choose appropriate words for the letter."],
    ["assumption", "假设", "The plan is based on a wrong assumption."],
    ["available", "可获得的", "Tickets are available online."],
    ["benefit", "益处；受益", "Exercise benefits both body and mind."],
    ["capacity", "能力；容量", "The hall has a capacity of 500 people."],
    ["challenge", "挑战", "The task is a real challenge."],
    ["circumstance", "情况；环境", "We must act according to the circumstances."],
    ["commitment", "承诺；投入", "Success requires commitment."],
    ["compete", "竞争；比赛", "Teams from different schools will compete."],
    ["complex", "复杂的", "The problem is more complex than it looks."],
    ["consequence", "结果；后果", "Every choice has a consequence."],
    ["constant", "不断的；持续的", "Constant practice improves pronunciation."],
    ["contribute", "贡献；导致", "Everyone can contribute to the project."],
    ["convenient", "方便的", "Online payment is convenient."],
    ["convince", "使信服", "The evidence convinced the audience."],
    ["critical", "关键的；批判的", "Critical thinking is important."],
    ["decline", "下降；拒绝", "The number of visitors declined."],
    ["demonstrate", "展示；证明", "The experiment demonstrates the theory."],
    ["despite", "尽管", "Despite the rain, they continued."],
    ["determine", "决定；查明", "Your attitude determines your progress."],
    ["efficient", "高效的", "This is an efficient way to learn."],
    ["emphasis", "强调", "The course places emphasis on reading."],
    ["encounter", "遇到；遭遇", "We may encounter difficulties."],
    ["essential", "必要的；本质的", "Sleep is essential for health."],
    ["estimate", "估计", "It is hard to estimate the cost."],
    ["evidence", "证据", "There is clear evidence for the claim."],
    ["expand", "扩大；扩展", "The company plans to expand overseas."],
    ["figure", "数字；人物；认为", "The figure shows a clear trend."],
    ["flexible", "灵活的", "A flexible plan can save time."],
    ["guarantee", "保证", "Practice cannot guarantee success, but it helps."],
    ["illustrate", "说明；阐明", "The example illustrates the rule."],
    ["impact", "影响；冲击", "Technology has a great impact on life."],
    ["imply", "暗示", "His words imply a different meaning."],
    ["indicate", "表明；指示", "The sign indicates the exit."]
  ],
  ket: [
    ["address", "地址", "Please write your address here."],
    ["airport", "机场", "We arrived at the airport early."],
    ["answer", "回答；答案", "Can you answer this question?"],
    ["apartment", "公寓", "They live in a small apartment."],
    ["appointment", "约定；预约", "I have a doctor's appointment."],
    ["arrive", "到达", "What time did you arrive?"],
    ["aunt", "姑母；姨母", "My aunt lives in London."],
    ["bathroom", "浴室；洗手间", "The bathroom is upstairs."],
    ["beautiful", "美丽的", "It is a beautiful day."],
    ["because", "因为", "I stayed home because it rained."],
    ["bicycle", "自行车", "He goes to school by bicycle."],
    ["birthday", "生日", "Her birthday is in May."],
    ["breakfast", "早餐", "I usually have eggs for breakfast."],
    ["bridge", "桥", "There is a bridge over the river."],
    ["camera", "照相机", "She took a camera on holiday."],
    ["careful", "小心的；仔细的", "Be careful when you cross the road."],
    ["cheap", "便宜的", "This bag is cheap but useful."],
    ["cinema", "电影院", "We went to the cinema last night."],
    ["clothes", "衣服", "Put your clothes in the bag."],
    ["cloudy", "多云的", "It is cloudy today."],
    ["coffee", "咖啡", "Would you like some coffee?"],
    ["college", "学院；大学", "My brother studies at college."],
    ["comfortable", "舒服的", "This chair is comfortable."],
    ["cook", "做饭；厨师", "My father can cook well."],
    ["country", "国家；乡村", "Which country are you from?"],
    ["dangerous", "危险的", "Swimming here is dangerous."],
    ["delicious", "美味的", "The soup is delicious."],
    ["different", "不同的", "They have different hobbies."],
    ["difficult", "困难的", "This question is difficult."],
    ["doctor", "医生", "The doctor checked my eyes."],
    ["evening", "晚上", "See you this evening."],
    ["expensive", "昂贵的", "That jacket is too expensive."],
    ["family", "家庭；家人", "My family is very friendly."],
    ["favourite", "最喜欢的", "Blue is my favourite colour."],
    ["festival", "节日", "The festival starts tomorrow."],
    ["friendly", "友好的", "The new student is friendly."],
    ["garden", "花园", "There are flowers in the garden."],
    ["holiday", "假期", "We had a great holiday."],
    ["homework", "家庭作业", "Finish your homework first."],
    ["hospital", "医院", "She works in a hospital."],
    ["kitchen", "厨房", "Mum is in the kitchen."],
    ["library", "图书馆", "I borrowed a book from the library."],
    ["message", "信息；留言", "I sent him a message."],
    ["museum", "博物馆", "The museum is closed today."],
    ["question", "问题", "I have a question."],
    ["restaurant", "餐馆", "We ate at a small restaurant."],
    ["station", "车站", "The station is near here."],
    ["weather", "天气", "The weather is sunny."],
    ["weekend", "周末", "What do you do at the weekend?"],
    ["yesterday", "昨天", "I saw her yesterday."]
  ],
  pet: [
    ["advantage", "优点；优势", "One advantage of cycling is that it is cheap."],
    ["advertise", "做广告", "They advertise the event online."],
    ["allow", "允许", "Mobile phones are not allowed here."],
    ["although", "虽然", "Although it was late, we kept working."],
    ["amount", "数量", "A large amount of water was wasted."],
    ["arrangement", "安排", "We made an arrangement to meet at six."],
    ["article", "文章", "She wrote an article for the school magazine."],
    ["audience", "观众", "The audience enjoyed the show."],
    ["average", "平均的；平均数", "The average temperature is rising."],
    ["behaviour", "行为", "Good behaviour is important in class."],
    ["belong", "属于", "This book belongs to me."],
    ["borrow", "借入", "Can I borrow your pen?"],
    ["celebrate", "庆祝", "We celebrate the festival with family."],
    ["choice", "选择", "You have a choice between two courses."],
    ["communicate", "交流", "People communicate in many ways."],
    ["community", "社区", "The community built a new park."],
    ["compare", "比较", "Compare the two pictures."],
    ["competition", "比赛；竞争", "She won the writing competition."],
    ["condition", "状况；条件", "The road is in poor condition."],
    ["continue", "继续", "Please continue reading."],
    ["culture", "文化", "Food is part of culture."],
    ["decision", "决定", "It was a difficult decision."],
    ["describe", "描述", "Can you describe the person?"],
    ["develop", "发展；培养", "Reading helps develop language skills."],
    ["difference", "差异", "There is a big difference between them."],
    ["education", "教育", "Education changes lives."],
    ["environment", "环境", "We should protect the environment."],
    ["experience", "经历；经验", "Travel is a useful experience."],
    ["explain", "解释", "Please explain your answer."],
    ["improve", "提高", "Practice will improve your speaking."],
    ["include", "包括", "The price includes breakfast."],
    ["information", "信息", "The website gives useful information."],
    ["interest", "兴趣", "She has an interest in music."],
    ["journey", "旅程", "The journey took two hours."],
    ["knowledge", "知识", "Books give us knowledge."],
    ["necessary", "必要的", "It is necessary to check the time."],
    ["opinion", "观点", "What is your opinion?"],
    ["ordinary", "普通的", "It was an ordinary day."],
    ["organize", "组织", "They organize activities for students."],
    ["pollution", "污染", "Air pollution is a serious problem."],
    ["population", "人口", "The population of the city is growing."],
    ["prepare", "准备", "We need to prepare for the exam."],
    ["probably", "可能", "He will probably come later."],
    ["promise", "承诺", "I promise to help you."],
    ["protect", "保护", "We must protect animals."],
    ["purpose", "目的", "What is the purpose of the meeting?"],
    ["receive", "收到", "Did you receive my email?"],
    ["recommend", "推荐", "I recommend this book."],
    ["reduce", "减少", "We should reduce waste."],
    ["result", "结果", "The result surprised everyone."]
  ]
};
